import React from 'react';
import { X, Printer, Download, CheckCircle2, ShieldAlert } from 'lucide-react';
import {
  AuraPatientProfile,
  RiskEvaluation,
  SymptomStatisticalEvidence
} from '../types/health';
import { computeBmi } from '../engine/auraHealthEngine';

interface AuraReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  profile: AuraPatientProfile;
  heartRisk: RiskEvaluation;
  diabetesRisk: RiskEvaluation;
  evidenceList: SymptomStatisticalEvidence[];
  recommendations: { title: string; desc: string }[];
}

export const AuraReportModal: React.FC<AuraReportModalProps> = ({
  isOpen,
  onClose,
  profile,
  heartRisk,
  diabetesRisk,
  evidenceList,
  recommendations
}) => {
  if (!isOpen) return null;

  const bmiInfo = computeBmi(profile.weightKg, profile.heightCm, profile.age);
  const reportDate = new Date().toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadTxt = () => {
    const lines = [
      `=======================================================`,
      `AURAHEALTH NEXUS - CLINICAL INTELLIGENCE DOSSIER`,
      `=======================================================`,
      `Date: ${reportDate}`,
      `Patient Identifier: ${profile.name || 'Anonymous Patient'}`,
      `Demographics: Age ${profile.age} | Sex ${profile.gender} | Height ${profile.heightCm} cm | Weight ${profile.weightKg} kg`,
      `Calculated BMI: ${bmiInfo.bmi} (${bmiInfo.category})`,
      `Lifestyle Factors:`,
      `  * Smoking Habit: ${profile.smoking}`,
      `  * Physical Activity: ${profile.physicalActivity}`,
      `  * Sleep / Night Breathing: ${profile.sleepQuality}`,
      `  * Family Genetics: ${profile.familyHistory ? 'Positive (+)' : 'Negative (-)'}`,
      ``,
      `--- BAYESIAN POSTERIOR PROBABILITY SYNTHESIS ---`,
      `Coronary Heart Disease Risk: ${heartRisk.percentage.toFixed(1)}% [${heartRisk.level}]`,
      `Type-2 Diabetes Mellitus Risk: ${diabetesRisk.percentage.toFixed(1)}% [${diabetesRisk.level}]`,
      ``,
      `--- SYMPTOM STATISTICAL SIGNIFICANCE (Chi-Square, N=2,500 Cohort) ---`,
      ...evidenceList.map(
        (e) => `* ${e.label} [${e.reportedValue}]: p = ${e.pValue} -> ${e.isSignificant ? 'Statistically Verified' : 'Incidental Variation'}`
      ),
      ``,
      `--- PERSONALIZED CLINICAL ACTION DIRECTIVES ---`,
      ...recommendations.map((r, i) => `${i + 1}. ${r.title}: ${r.desc}`),
      ``,
      `CLINICAL GOVERNANCE NOTICE:`,
      `This dossier is generated by a Bayesian Decision Support demonstration`,
      `and does not replace formal physician examination or laboratory confirmation.`
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `AuraHealth_Nexus_${(profile.name || 'Patient').replace(/\s+/g, '_')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-md flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-[#0B132B] rounded-2xl border border-cyan-500/25 shadow-2xl shadow-cyan-500/10 max-w-2xl w-full max-h-[90vh] flex flex-col overflow-hidden text-slate-200">
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-cyan-500/20 flex items-center justify-between bg-slate-900/80">
          <div>
            <h3 className="font-semibold text-white text-base flex items-center gap-2">
              <span className="w-2.5 h-2.5 rounded-full bg-cyan-400" />
              Clinical Intelligence Dossier: {profile.name || 'Patient'}
            </h3>
            <p className="text-xs text-slate-400">
              Generated on {reportDate} &middot; Bayesian DAG &amp; &chi;&sup2; Model Output
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-white hover:bg-slate-800 rounded-xl transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto space-y-5 text-xs text-slate-300">
          {/* Patient Quick Vitals Bar */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 p-3.5 bg-slate-900/80 border border-slate-800 rounded-xl text-center">
            <div>
              <span className="text-[10px] text-slate-400 uppercase font-mono">Age / Sex</span>
              <p className="font-semibold text-white mt-0.5">
                {profile.age} yrs &middot; {profile.gender}
              </p>
            </div>
            <div>
              <span className="text-[10px] text-slate-400 uppercase font-mono">Weight / BMI</span>
              <p className="font-semibold text-cyan-300 mt-0.5">
                {profile.weightKg} kg ({bmiInfo.bmi})
              </p>
            </div>
            <div>
              <span className="text-[10px] text-slate-400 uppercase font-mono">Physical Activity</span>
              <p className="font-semibold text-white mt-0.5 truncate">
                {profile.physicalActivity.split('/')[0]}
              </p>
            </div>
            <div>
              <span className="text-[10px] text-slate-400 uppercase font-mono">Sleep Quality</span>
              <p className="font-semibold text-white mt-0.5 truncate">
                {profile.sleepQuality.includes('Possible') ? 'Apnea Risk' : 'Normal'}
              </p>
            </div>
          </div>

          {/* Risk Synthesis Overview */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
            <div className="p-3.5 bg-slate-900/60 border border-cyan-500/20 rounded-xl">
              <span className="text-[10px] uppercase font-mono font-bold text-cyan-400">
                Coronary Heart Disease
              </span>
              <div className="flex items-baseline gap-2 mt-1">
                <span className="text-2xl font-bold font-mono text-cyan-300">
                  {heartRisk.percentage.toFixed(1)}%
                </span>
                <span
                  className="text-[11px] font-semibold px-2 py-0.5 rounded-full border"
                  style={{
                    backgroundColor: heartRisk.badgeBg,
                    borderColor: heartRisk.badgeBorder,
                    color: heartRisk.badgeText
                  }}
                >
                  {heartRisk.level}
                </span>
              </div>
            </div>

            <div className="p-3.5 bg-slate-900/60 border border-cyan-500/20 rounded-xl">
              <span className="text-[10px] uppercase font-mono font-bold text-cyan-400">
                Type-2 Diabetes Mellitus
              </span>
              <div className="flex items-baseline gap-2 mt-1">
                <span className="text-2xl font-bold font-mono text-cyan-300">
                  {diabetesRisk.percentage.toFixed(1)}%
                </span>
                <span
                  className="text-[11px] font-semibold px-2 py-0.5 rounded-full border"
                  style={{
                    backgroundColor: diabetesRisk.badgeBg,
                    borderColor: diabetesRisk.badgeBorder,
                    color: diabetesRisk.badgeText
                  }}
                >
                  {diabetesRisk.level}
                </span>
              </div>
            </div>
          </div>

          {/* Statistical Evidence Breakdown */}
          <div>
            <h4 className="text-xs font-semibold text-white uppercase tracking-wider mb-2 font-mono">
              &chi;&sup2; Symptom Significance Findings
            </h4>
            <div className="space-y-2">
              {evidenceList.map((item) => (
                <div
                  key={item.id}
                  className="p-2.5 bg-slate-900/70 border border-slate-800 rounded-lg flex items-center justify-between gap-3 text-[11px]"
                >
                  <div>
                    <span className="font-semibold text-white">{item.label}</span>:{' '}
                    <span className="text-cyan-300 font-mono">{item.reportedValue}</span>
                  </div>
                  <span
                    className={`px-2 py-0.5 rounded-full font-mono text-[10px] border ${
                      item.isSignificant
                        ? 'bg-emerald-500/15 text-emerald-300 border-emerald-500/30'
                        : 'bg-slate-800 text-slate-400 border-slate-700'
                    }`}
                  >
                    p = {item.pValue} ({item.isSignificant ? 'Verified' : 'Incidental'})
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Action Recommendations */}
          <div>
            <h4 className="text-xs font-semibold text-white uppercase tracking-wider mb-2 font-mono">
              Priority Clinical Action Plan
            </h4>
            <div className="space-y-2">
              {recommendations.map((rec, i) => (
                <div key={rec.title} className="p-2.5 bg-slate-900/70 border border-slate-800 rounded-lg">
                  <div className="font-semibold text-cyan-300 text-[11px]">
                    {i + 1}. {rec.title}
                  </div>
                  <p className="text-[11px] text-slate-400 mt-0.5 leading-relaxed">{rec.desc}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Disclaimer */}
          <div className="p-3 bg-slate-900/80 border-l-2 border-cyan-400 rounded-r-lg text-[10px] text-slate-400 leading-normal flex items-start gap-2">
            <ShieldAlert className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />
            <p>
              This document is generated by AuraHealth Nexus for clinical decision-support and educational demonstrations. It is not an automated medical diagnostic tool and should be reviewed by an authorized healthcare professional.
            </p>
          </div>
        </div>

        {/* Modal Footer Actions */}
        <div className="px-6 py-3.5 border-t border-cyan-500/20 bg-slate-900/90 flex items-center justify-between gap-3">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-xs font-medium text-slate-400 hover:text-white transition-colors cursor-pointer"
          >
            Close
          </button>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-300 bg-slate-800 hover:bg-slate-700 rounded-xl border border-slate-700 transition-colors cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5 text-slate-400" />
              <span>Print</span>
            </button>
            <button
              type="button"
              onClick={handleDownloadTxt}
              className="flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-bold text-slate-950 bg-gradient-to-r from-blue-600 to-cyan-500 hover:from-blue-500 hover:to-cyan-400 rounded-xl shadow-md shadow-cyan-500/20 transition-all cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download (.TXT)</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
